### ISSUE TITLE
Code Actions won't apply correctly

### ISSUE THREAD

**Issue by xldenis** [tomv564/LSP#209]
I can't tell if this is an issue with [HIE]() or with LSP but I can't seem to get code-actions applying correctly. 

HIE correctly suggests code hints like so:

![image](https://user-images.githubusercontent.com/451373/32975975-5a23cb7e-cbd3-11e7-8db4-52f1f93c27cc.png)

But when I attempt to apply them it causes a new tab to a file called `changes` to get opened up.

![image](https://user-images.githubusercontent.com/451373/32975983-7101f7a8-cbd3-11e7-8e75-b8af742e1012.png)

This occurs on version `Version 0.1.0.0, Git revision 9e39517408fd2948c60ac49e56267c93051f8878 (1066 commits) x86_64` with LSP v0.4.0

Sublime logs:

```
2017-11-17 20:10:41.111253 [ThreadId 14] - applyHint:diff=WorkspaceEdit {_changes = Just (fromList [(Uri {getUri = "file:///Users/xavier/Code/xldenis/hake/src/Hake/Run.hs"},List [])]), _documentChanges = Nothing}:
2017-11-17 20:10:41.171287 [ThreadId 14] - applyOneCmd:file="/Users/xavier/Code/xldenis/hake/src/Hake/Run.hs":
2017-11-17 20:10:41.172049 [ThreadId 14] - applyOneCmd:res=Right (WorkspaceEdit {_changes = Just (fromList [(Uri {getUri = "file:///Users/xavier/Code/xldenis/hake/src/Hake/Run.hs"},List [])]), _documentChanges = Nothing}):
LSP: <--  workspace/applyEdit
LSP:      {'edit': {'changes': {'file:///Users/xavier/Code/xldenis/hake/src/Hake/Run.hs': []}}}
Unable to open /Users/xavier/Code/xldenis/hake/src/Hake/changes
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "plugin.core.edit in /Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package", line 44, in run
  File "plugin.core.edit in /Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package", line 44, in <genexpr>
  File "plugin.core.edit in /Users/xavier/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package", line 68, in create_region
TypeError: string indices must be integers
```

**Comment by xldenis** [comment]
https://github.com/haskell/haskell-ide-engine/issues/356 cross-referencing

**Comment by tomv564** [comment]
This is an LSP problem I recently introduced, apologies.
Fixed in commit https://github.com/tomv564/LSP/commit/629d10539ffbc7ad65eb9dc619d047405bf7373f

**Comment by xldenis** [comment]
Thanks, I'll update from git and see if this resolves my problem.

**Comment by xldenis** [comment]
Hmm they still don't apply but the logs show that LSP is no longer raising an error. This may just indicate that HIE isn't responding properly?

**Comment by tomv564** [comment]
Can you retry with the `log_debug` setting set to true in the LSP settings? There is also a `log_payloads` setting in `settings.py` (we'll add this to the settings soon) which you can set to true for extra details.
Alternatively, does HIE have logging output?

**Comment by xldenis** [comment]
I've enabled all the logging options I found in HIE and LSP here's what I got

```
haskell-lsp:Starting up server ...:
2017-11-23 22:08:59.448923 [ThreadId 11] - ---> {"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {"capabilities": {"workspace": {"applyEdit": true}, "textDocument": {"completion": {"completionItem": {"snippetSupport": true}}, "synchronization": {"didSave": true}}}, "rootPath": "/Users/xavier/Code/xldenis/ill", "rootUri": "file:///Users/xavier/Code/xldenis/ill", "processId": 79892}}:
2017-11-23 22:08:59.45184 [ThreadId 11] - haskell-lsp:initializeRequestHandler: setting current dir to project root:/Users/xavier/Code/xldenis/ill:
LSP:  --> initialized
LSP: hie client registered for window 5
2017-11-23 22:08:59.452641 [ThreadId 12] - <--2--{"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"willSave":false,"willSaveWaitUntil":false,"save":{"includeText":false}},"hoverProvider":true,"completionProvider":{"resolveProvider":true,"triggerCharacters":["."]},"definitionProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":true,"executeCommandProvider":{"commands":["applyrefact:applyOne","hare:demote"]}}},"jsonrpc":"2.0","id":1}:
2017-11-23 22:08:59.453423 [ThreadId 11] - ---> {"jsonrpc": "2.0", "method": "initialized", "params": {}}:
2017-11-23 22:08:59.455698 [ThreadId 15] - ****** reactor: processing Initialized Notification:
2017-11-23 22:08:59.456486 [ThreadId 12] - <--2--{"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"registerOptions":{"documentSelector":{"language":"haskell"}},"method":"workspace/executeCommand","id":"hare:demote"}]}}:
LSP:  --> textDocument/didOpen
LSP: <--  client/registerCapability
LSP: Unhandled request client/registerCapability
2017-11-23 22:08:59.494693 [ThreadId 11] - ---> {"jsonrpc": "2.0", "method": "textDocument/didOpen", "params": {"textDocument": {"version": 0, "languageId": "haskell", "text": "module Ill.Desugar\n( module Ill.Desugar\n, module X\n) where\n\nimport Ill.Syntax hiding (Expression(..), ty)\nimport Ill.Syntax.Core as C\n\nimport qualified Ill.Syntax as S\n\nimport Ill.Desugar.Trait as X\nimport Ill.Desugar.Cases as X\nimport Ill.Desugar.BinOp as X\n\nimport Control.Monad.State\n\nimport Data.Maybe\nimport Data.List\n\ntype Id = Name\n\n{-\n  Syntax definition for core lambda calculus representation\n\n  At this point all top level bindings should have cases pushed in,\n  traits should have been desugared.\n\n  Data constructors are still kept as implicit bindings\n  to variables with the name of the contrsuctor.\n-}\n\ndeclsToCore :: [Decl TypedAnn] -> CoreModule\ndeclsToCore decls = execState (mapM declToCore' decls) (Mod [] [])\n\ndeclToCore' :: Decl TypedAnn -> State CoreModule ()\ndeclToCore' (a :< Value nm [([], exp)]) = do\n  let bindExp = (toCore exp)\n\n  modify $ \\m -> m { bindings = NonRec binder bindExp : bindings m }\n  where\n  unforall (Forall tVars _) = tVars\n  unforall _                = []\n\n  binder = Id { varName = nm, idTy = fromTyAnn a, usage = Used }\ndeclToCore' (_ :< Data nm args conses) = do\n  let cons' = map (\\cons ->\n        case unwrapProduct cons of\n          (TConstructor consNm : args) -> (consNm, (length args, getConstructorType cons))\n        ) conses\n  modify $ \\m -> m { constructors = cons' ++ constructors m }\n  where\n  getConstructorType ty = let\n    (TConstructor tyCons : tys) = unwrapProduct ty\n    retTy = foldl TAp (TConstructor nm) (map TVar args)\n    in generalize $ foldr tFn retTy tys\ndeclToCore' (_) = pure ()\n\n{-\n  Get the type applications needed for a type annotation\n-}\ngetTypeApps :: TypedAnn -> [CoreExp]\ngetTypeApps t = map (C.Type . snd) subst\n  where\n  subst = case join $ subsume <$> (pure . unForall . polyTy $ S.ty t) <*> ((instTy $ S.ty t)) of\n    Just l -> filter (\\(v, _) -> v `elem` boundVars (polyTy $ S.ty t)) l\n    Nothing -> []\n\n  boundVars (Forall vs _) = vs\n  boundVars _ = []\n\n  unForall (Forall _ t) = t\n  unForall t = t\n\ntoCore :: Expr TypedAnn -> CoreExp\ntoCore var@(a :< S.Var nm) = foldl App (Var nm) (getTypeApps a)\ntoCore cons@(a :< S.Constructor nm) = foldl App (Var nm) (getTypeApps a)\ntoCore (_ :< S.Case scrut alts) = Case (toCore scrut) (toAlts alts)\ntoCore (_ :< S.Assign names exprs) = error \"assignments must be desugared in blocks\"\ntoCore (a :< S.Apply lam args) = foldl App (toCore lam) $ (map toCore args) ++ (getTypeApps a)\ntoCore (_ :< S.BinOp op left right) = error \"binops should have been desugared to assigns\"\ntoCore (_ :< S.If cond left right) = Case (toCore cond)\n  [ ConAlt \"True\" [] (toCore left)\n  , ConAlt \"False\" [] (toCore right)\n  ]\ntoCore (lAnn :< S.Lambda bind exp) = let\n  vars = map toVar bind\n  tyVars = map toTyVar (boundVars $ fromTyAnn lAnn)\n  in foldr Lambda (toCore exp) (tyVars ++ vars)\n  where\n  toVar (a :< S.PVar nm) = Id { varName = nm, idTy = fromTyAnn a, usage = Used }\n  isVarPat (_ :< S.PVar _) = True\n  isVarPat _ = False\n\n  boundVars (Forall vs _) = vs\n  boundVars _ = []\n\n  toTyVar tyvar = TyVar { varName = tyvar, kind = Star }\ntoCore (_ :< S.Body exps) = toCore' exps\n  where\n  toCore' :: [Expr TypedAnn] -> CoreExp\n  toCore' ((_ :< a@(S.Assign _ _ )): []) = error (show a) -- i think? i dont like this :(\n  toCore' ((_ :< S.Assign names exprs) : others) = let\n    binders = map toBinder $ zip names exprs\n    toBinder (nm, expr) = NonRec (Id nm (typeOf expr) Used) (toCore expr)\n    in foldr Let (toCore' others) binders\n  toCore' [e] = toCore e\n  toCore' (e:others) = toCore e `mkSeq` (toCore' others)\n    where\n    mkSeq a b = (App (App (Var \"seq\") a) b)\ntoCore (_ :< S.Literal lit ) = Lit lit\n\ntoAlts = map toAlt\n\ntoAlt (a :< Wildcard, e) = TrivialAlt $ toCore e\ntoAlt (_ :< PLit lit, exp) = LitAlt lit $ toCore exp\ntoAlt (_ :< Destructor n ps, exp) = ConAlt n (map toVar ps) $ toCore exp\n  where\n  toVar (a :< Wildcard) = Id \"\" (fromTyAnn a) NotUsed\n  toVar (a :< PVar nm)  = Id nm (fromTyAnn a) Used\n  toVar a = error (show a)\n", "uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}}}:
2017-11-23 22:08:59.512948 [ThreadId 15] - ****** reactor: processing NotDidOpenTextDocument:
2017-11-23 22:08:59.604717 [ThreadId 14] - dispatcherP: top of loop:
2017-11-23 22:08:59.605089 [ThreadId 14] - got request with id: Nothing:
Using hoogle db at: /Users/xavier/.hoogle/default-haskell-5.0.13.hoo:
2017-11-23 22:08:59.608648 [ThreadId 14] - dispatcherP: top of loop:
2017-11-23 22:08:59.608749 [ThreadId 12] - <--2--{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Using hoogle db at: /Users/xavier/.hoogle/default-haskell-5.0.13.hoo"}}:
2017-11-23 22:08:59.609029 [ThreadId 14] - got request with id: Nothing:
2017-11-23 22:08:59.757598 [ThreadId 14] - dispatcherP: top of loop:
2017-11-23 22:08:59.758194 [ThreadId 14] - got request with id: Nothing:
2017-11-23 22:08:59.758778 [ThreadId 14] - Processing request as version matches:
2017-11-23 22:08:59.838272 [ThreadId 14] - dispatcherP: top of loop:
2017-11-23 22:08:59.838537 [ThreadId 14] - got request with id: Nothing:
2017-11-23 22:08:59.839375 [ThreadId 14] - Processing request as version matches:
LSP: <--  textDocument/publishDiagnostics
2017-11-23 22:08:59.9826 [ThreadId 12] - <--2--{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs","diagnostics":[{"severity":4,"range":{"start":{"line":35,"character":42},"end":{"line":38,"character":68}},"source":"hlint","message":"Redundant bracket\nFound:\n  do let bindExp = (toCore exp)\n   modify $ \\ m -> m{bindings = NonRec binder bindExp : bindings m}\nWhy not:\n  do let bindExp = toCore exp\n   modify $ \\ m -> m{bindings = NonRec binder bindExp : bindings m}\n"},{"severity":2,"range":{"start":{"line":55,"character":12},"end":{"line":55,"character":15}},"source":"hlint","message":"Redundant bracket\nFound:\n  (_)\nWhy not:\n  _\n"},{"severity":4,"range":{"start":{"line":63,"character":74},"end":{"line":63,"character":93}},"source":"hlint","message":"Redundant bracket\nFound:\n  ((instTy $ S.ty t))\nWhy not:\n  (instTy $ S.ty t)\n"},{"severity":4,"range":{"start":{"line":78,"character":58},"end":{"line":78,"character":94}},"source":"hlint","message":"Redundant bracket\nFound:\n  (map toCore args) ++ (getTypeApps a)\nWhy not:\n  (map toCore args) ++ getTypeApps a\n"},{"severity":4,"range":{"start":{"line":78,"character":58},"end":{"line":78,"character":94}},"source":"hlint","message":"Redundant bracket\nFound:\n  (map toCore args) ++ (getTypeApps a)\nWhy not:\n  map toCore args ++ (getTypeApps a)\n"},{"severity":4,"range":{"start":{"line":100,"character":10},"end":{"line":100,"character":40}},"source":"hlint","message":"Use list literal pattern\nFound:\n  ((_ :< a@(S.Assign _ _)) : [])\nWhy not:\n  [(_ :< a@(S.Assign _ _))]\n"},{"severity":4,"range":{"start":{"line":102,"character":14},"end":{"line":102,"character":44}},"source":"hlint","message":"Use zipWith\nFound:\n  map toBinder $ zip names exprs\nWhy not:\n  zipWith (curry toBinder) names exprs\n"},{"severity":4,"range":{"start":{"line":106,"character":23},"end":{"line":106,"character":56}},"source":"hlint","message":"Redundant bracket\nFound:\n  toCore e `mkSeq` (toCore' others)\nWhy not:\n  toCore e `mkSeq` toCore' others\n"},{"severity":4,"range":{"start":{"line":108,"character":16},"end":{"line":108,"character":43}},"source":"hlint","message":"Redundant bracket\nFound:\n  (App (App (Var \"seq\") a) b)\nWhy not:\n  App (App (Var \"seq\") a) b\n"}]}}:
hie: /Users/xavier/.stack/programs/x86_64-osx/ghc-8.2.1/lib/ghc-8.2.1/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!):
LSP:  --> textDocument/didSave
2017-11-23 22:09:06.273538 [ThreadId 11] - ---> {"jsonrpc": "2.0", "method": "textDocument/didSave", "params": {"textDocument": {"uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}}}:
LSP:  --> textDocument/codeAction
2017-11-23 22:09:14.072273 [ThreadId 11] - ---> {"jsonrpc": "2.0", "id": 2, "method": "textDocument/codeAction", "params": {"context": {"diagnostics": [{"range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}, "source": "hlint", "message": "Redundant bracket\nFound:\n  (_)\nWhy not:\n  _\n", "severity": 2}]}, "textDocument": {"uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}, "range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}}}:
LSP:  --> textDocument/codeAction
2017-11-23 22:09:14.685736 [ThreadId 11] - ---> {"jsonrpc": "2.0", "id": 3, "method": "textDocument/codeAction", "params": {"context": {"diagnostics": [{"range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}, "source": "hlint", "message": "Redundant bracket\nFound:\n  (_)\nWhy not:\n  _\n", "severity": 2}]}, "textDocument": {"uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}, "range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}}}:
LSP:  --> textDocument/codeAction
2017-11-23 22:09:14.902591 [ThreadId 11] - ---> {"jsonrpc": "2.0", "id": 4, "method": "textDocument/codeAction", "params": {"context": {"diagnostics": [{"range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}, "source": "hlint", "message": "Redundant bracket\nFound:\n  (_)\nWhy not:\n  _\n", "severity": 2}]}, "textDocument": {"uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}, "range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}}}:
LSP:  --> textDocument/codeAction
2017-11-23 22:09:15.102978 [ThreadId 11] - ---> {"jsonrpc": "2.0", "id": 5, "method": "textDocument/codeAction", "params": {"context": {"diagnostics": [{"range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}, "source": "hlint", "message": "Redundant bracket\nFound:\n  (_)\nWhy not:\n  _\n", "severity": 2}]}, "textDocument": {"uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}, "range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}}}:
LSP:  --> textDocument/codeAction
2017-11-23 22:09:15.319656 [ThreadId 11] - ---> {"jsonrpc": "2.0", "id": 6, "method": "textDocument/codeAction", "params": {"context": {"diagnostics": [{"range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}, "source": "hlint", "message": "Redundant bracket\nFound:\n  (_)\nWhy not:\n  _\n", "severity": 2}]}, "textDocument": {"uri": "file:///Users/xavier/Code/xldenis/ill/src/Ill/Desugar.hs"}, "range": {"start": {"line": 55, "character": 12}, "end": {"line": 55, "character": 15}}}}:
```

**Comment by xldenis** [comment]
The closes thing to an error or lead on the problem I can find is the line

```
hie: /Users/xavier/.stack/programs/x86_64-osx/ghc-8.2.1/lib/ghc-8.2.1/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!):
```

**Comment by tomv564** [comment]
I tried this code action with a simple generated stack LTS 9 project  by duplicating the `import Lib` in Main.hs:

```
LSP:  --> textDocument/codeAction
LSP:      [{'command': 'applyrefact:applyOne', 'arguments': [{'start_pos': {'character': 0, 'line': 2}, 'file': 'file:///Users/tomv/Projects/tomv564/hello-world-hs/app/Main.hs'}], 'title': 'Apply hint:Use fewer imports'}]
LSP:  --> workspace/executeCommand
LSP: <--  workspace/applyEdit
LSP:      {'edit': {'changes': {'file:///Users/tomv/Projects/tomv564/hello-world-hs/app/Main.hs': []}}}
```

While HIE logs:

```
2017-11-25 15:30:29.580253 [ThreadId 10] - applyHint:ideas=[/private/var/folders/_r/0qgd5krn3s7f6_n6t6kn3v100000gn/T/ghc-mod73563/Main16807282475249.hs:1:1: Ignore: Use module export list:LSP:
Found::
      {}
module Main where:
Why not::
module Main (module Main) where:
Note: An explicit list is usually better:

,/private/var/folders/_r/0qgd5krn3s7f6_n6t6kn3v100000gn/T/ghc-mod73563/Main16807282475249.hs:3:1: Warning: Use fewer imports:
Found::
import Lib:
import Lib:
Why not::
import Lib:
]:
2017-11-25 15:30:29.595122 [ThreadId 10] - applyHint:diff=WorkspaceEdit {_changes = Just (fromList [(Uri {getUri = "file:///Users/tomv/Projects/tomv564/hello-world-hs/app/Main.hs"},List [])]), _documentChanges = Nothing}:
2017-11-25 15:30:29.598587 [ThreadId 10] - applyOneCmd:file="/Users/tomv/Projects/tomv564/hello-world-hs/app/Main.hs":
2017-11-25 15:30:29.599093 [ThreadId 10] - applyOneCmd:res=Right (WorkspaceEdit {_changes = Just (fromList [(Uri {getUri = "file:///Users/tomv/Projects/tomv564/hello-world-hs/app/Main.hs"},List [])]), _documentChanges = Nothing}):
```

It looks like the handler for the `applyrefact:applyOne` command (`applyHint`?) is having difficulty producing edits for the given refactoring title?

**Comment by xldenis** [comment]
Yea, from what I can tel lthe issue lies on the HIE side of things but I'm having a hard time getting an answer / input on that side.

**Comment by xldenis** [comment]
I'm going to close this for now.
