### ISSUE TITLE
How to handle windows with multiple root folders?

### ISSUE THREAD

**Issue by tomv564** [tomv564/LSP#33]
The LSP package currently handles windows with multiple folders by finding a common prefix.

As discovered in #24, a common usage with Sublime workspaces is to link in whole trees of projects, perhaps even from multiple drives (e.g. `C:\Users\Tom\Projects` and `D:\Work\`)

For this scenario, it is increasingly unlikely that we can find a common prefix to give the language server as `rootUri`.

Looking at the language server protocol, the workspace concept (of which there is only one in a language server process) offers these actions:

`workspace/symbols` (would you really want to execute this across both drives ?) `workspace/didChangeConfiguration` (configuration is likely to be project-specific, if anything)

An improvement would be to create an LSP instance per `window.folders()`.

Users who choose to mount the parent folder of multiple projects will have to accept that:
* workspace symbol listing is for projects
* The LSP package will not be able to help with per-project configuration.

**Comment by randy3k** [comment]
And it should also handle the case with no folders, i.e. when editing signal files.

**Comment by tomv564** [comment]
This has been solved by #81 (only use first folder) and #126 (support single files)

**Comment by haferburg** [comment]
This issue is still mentioned on https://github.com/tomv564/LSP#troubleshooting

**Comment by tomv564** [comment]
Thanks, pointed it to issue #82 instead!
